[package]
name = "r2dma"
version = "0.1.0"
authors = ["SF-Zhou <sfzhou.scut@gmail.com>"]
edition = "2021"
homepage = "https://crates.io/crates/r2dma"
repository = "https://crates.io/crates/r2dma"
description = "A Rust RDMA library."
license = "MIT OR Apache-2.0"

[dependencies]
derse = "0"
libc = "0"
nix = { version = "0", features = ["event"] }
serde = { version = "1", features = ["derive"] }
toml = "0"
tracing = "0"
tracing-subscriber = "0"

[build-dependencies]
bindgen = { version = "0", features = ["experimental"] }
pkg-config = "0"

[features]
debug = []
